-- \ Universal Remote Firer By TringForAllTheBadges //


-- [Games Tested On]

-- https://www.roblox.com/games/14570378822/Bodybuilder-Simulator [Open Rare Eggs]
-- https://www.roblox.com/games/15338697306/Go-Kart-Race-Simulator [Infinite Wins]
-- https://www.roblox.com/games/15352354257/Ball-Eating-Simulator [Collect Badges / 3]
-- https://www.roblox.com/games/15154513235/Kamehameha-Simulator [Rejoin if kicked / Unlimited Spins/ Inf power / Inf Pets / Claim all daily rewards / Reclaim Gifts]
-- https://www.roblox.com/games/87854376962069/The-1-000-000-Glass-Bridge [Rejoin if teleported/ Money Farming]
-- https://www.roblox.com/games/18150595865/Spirit-Bomb-Simulator [Rejoin if kicked / Unlimited Spins/ Inf power / Inf Pets / Claim all daily rewards / Reclaim Gifts]

local a = {}
local function b()
    for c, d in ipairs(game.ReplicatedStorage:GetDescendants()) do
        if d:IsA("RemoteEvent") or d:IsA("BindableEvent") or d:IsA("RemoteFunction") or d:IsA("BindableFunction") then
            table.insert(a, d)
        end
    end
end

local function e(...)
    local f = {...}
    for g, h in ipairs(a) do
        local i = h:GetFullName()
        if h:IsA("RemoteEvent") then
            h:FireServer(unpack(f))
        elseif h:IsA("BindableEvent") then
            h:Fire(unpack(f))
        elseif h:IsA("RemoteFunction") then
            spawn(function()
                local j, k = pcall(function()
                    return h:InvokeServer(unpack(f))
                end)
            end)
        elseif h:IsA("BindableFunction") then
            spawn(function()
                local j, k = pcall(function()
                    return h:Invoke(unpack(f))
                end)
            end)
        end
    end
end

b()

-- \ Arguments //
-- Add more args if you like, these are default.

e("Power", 900000)
e("Power", "90000")
e("ShootPwer", 900000)
e("ShootPwer", "90000")
e("Skulls", 900000)
e("Skulls", "90000")
e("Gold", 900000)
e("Gold", "90000")
e("Attack", 900000)
e("Attack", "90000")
e("Eggs", 999999)
e("Eggs", "900000")
e("Tap", 999999)
e("Tap", "900000")
e("Taps", 999999)
e("Taps", "900000")
e("Certz", 500)
e("Certz", "500")
e("Best", 500)
e("Best", "500")
e("Goals", 500)
e("Goals", "500")
e(900000000)
e("Kills", true)
e("Kills", 900000000000)
e("Kills", "900000000000")
e("Unlock All", true)
e("Unlock All", "true")
e("UnlockAll", true)
e("UnlockAll", "true")
e("9e9")
e("Money", 900000000000, true)
e("Strength", 900000000000)
e("Strength", "9000000000")
e("Stamina", 900000000000)
e({health = 900000000000, armor = 900000000000})
e(true, false, true)
e("Ammo", {bullets = 9e9, rockets = 9e9})
e("PowerUp", "SpeedBoost", true)
e("MissionComplete", {time = "10:30", score = 9e9})
e("Upgrade", "Weapon", "Shotgun")
e("Toggle", "Lights", true)
e("PlaySound", "Explosion")
e("Spawn", "Enemy", {type = "boss", level = 9e9})
e("PurchaseItem", "Weapon", "AssaultRifle")
e("ActivateAbility", "Invisibility")
e("Unlock", "CharacterSkin", "Ninja")
e("ToggleUI", "Inventory", true)
e("RestartLevel")
e("SendChatMessage", "Hello, world!")
e("UpdateSettings", {musicVolume = 0.7, soundVolume = 0.5})
e("RespawnPlayer")
e("CompleteQuest", "MainQuest", true)
e("XP", 900000)
e("LevelUp", 9000)
e("SkillUnlock", "DoubleJump")
e("RankUp", "Elite")
e("ExperienceGain", 9e9)
e("SkillUpgrade", "Strength", 9e9)
e("AchievementUnlock", "FirstVictory")
e("Progress", "Quest", "Explore")
e("SkillPoint", "Allocate", "Strength", 9e9)
e("Equip", "Weapon", "Sword")
e("Unequip", "Weapon", "Shotgun")
e("Reload", "Weapon", "SniperRifle")
e("Modify", "Weapon", "Pistol", {damage = 9e9, accuracy = 0.9})
e("Swap", "Weapon", "SMG", "Shotgun")
e("AddAttachment", "Weapon", "AssaultRifle", "Scope")
e("RemoveAttachment", "Weapon", "SniperRifle", "Suppressor")
e("Craft", "Weapon", "RocketLauncher")
e("Drop", "Weapon", "GrenadeLauncher")
e("KickPlayer", "Player123")
e("BanPlayer", "Player456")
e("ModifyStat", "Health", 999999)
e("GiveItem", "DiamondSword")
e("AddCurrency", "Gold", 100000)
e("UnlockAll", "Characters")
e("AwardBadge", "EpicBadge123")
e("GrantPermission", "Admin")
e("DisableSecurity", true)
e("AddMoney", 9e9)
e("SetMoney", 9e9)
e("DoubleMoney")
e("StealMoney", true)
e("StealMoney", "true")
e("ResetMoney", true)
e("ResetMoney", "true")
e("MultiplyMoney", 9e9)
e("HackMoney", 1000000)
e("AwardMoney", true)
e("AutoClick")
e("AutoCollect")
e("AutoSell")
e("InstantUpgrade")
e("SkipQuest")
e("AutoRebirth")
e("AutoUpgrade")
e("TeleportToZone", "HighLevelZone")
e("AutoFarm", "RareItem")
e("AutoPrestige")
e("AutoTrainSkill", "Strength")
e("AutoSpinWheel")
e("AutoOpenCrate", "LegendaryCrate")
e("AutoCompleteChallenge", "HardChallenge")
e("AutoLevelUp", "Character")
e("AutoClaimReward")
e("9e9")
e("True")
e("False")
e("9e9", true)
e(false)
e(true)
e("Points", 9e9)
e("Points", "90000000000")
e("Wins", 9e9)
e("Wins", "9e9")
e("Win", true)
e("Winner", true)
e("Balls", 9e9)
e("Owned", true)
e("Owned", 9e9)
e("Own", 9e9)
e("Own", true)
e("Value", 9e9)
e("Value", true)
e("Stage", 100)
e("Trophy", math.huge)
e("Ammo", 9e9)
e(Vector3.new(300, 150, 600))
e("Time", 9e9)
e("Time", "9e9")
e("Chickens", 9e9)
e("Chickens", "9e9")
e("Lives", "9e9")
e("Lives", 9e9)
e("Life", "9e9")
e("Life", 9e9)
e("Crowns", 9e9)
e("Crowns", "9e9")
e("Level", 100)
e("Level", "100")
e("Rebirth", 100)
e("Rebirth", "100")
e("XP", 100)
e("XP", "100")
e("Spins", 100)
e("Spins", 100)
e("Spin", 100)
e("Speed", 900)
e("Redeem", "true")
e("Redeem", "900")
e("Redeem", 9000)
e("Redeemed", "true")
e("Redeemed", true)
e("Speed", 900)
e("Spin", 9000)
e("Spins", 9000)
e("Cash", 100)
e("Cash", "100")
e("Coins", 100)
e("Coins", "100")
e("Dinero", 100)
e("Rank", 100)
e("Rank", "100")
e("Goals", 100)
e("Goals", "100")
e("Dinero", "100")
e("Damage", 9000000000000000000)
e("Damage", "900000000000000000000")
e("Win", 9000000000000000000)
e("Win", "900000000000000000000")
e("Wins", 9000000000000000000)
e("Wins", "900000000000000000000")
e("Hunger", 90000000)
e("Hunger", "9000000000000")
e("Body", 9000000000000)
e("Body", "9000000000000")
e("KillStreak", 9000000000000)
e("KillStreak", "9000000000000")
e("Health", "900000000")
e("Health", 900000000)
e("Energy", "900000000")
e("Energy", 900000000)
e("Melee", "900000000")
e("Melee", 900000000)
e("Reputation", 9000000000000000000)
e("Reputation", "900000000000000000000")
e("Distance", 9000000000000000000)
e("Distance", "900000000000000000000")
e("Nuke", "true")
e("Nuke", true)
e("Gems", 9000000000000000000)
e("Gems", "900000000000000000000")
e("Snow", 9000000000000000000)
e("Snow", "900000000000000000000")
e("Time", 9000000000000000000)
e("Time", "900000000000000000000")
e(90000000000)
e("90000000000")
e("Tokens", 5000)
e("Tokens", "5000")
e("Stars", 750)
e("Stars", "750")
e("Medals", 1200)
e("Medals", "1200")
e("Fragments", 300)
e("Fragments", "300")
e("Crystals", 10000)
e("Crystals", "10000")
e("Pearls", 1500)
e("Pearls", "1500")
e("Rubies", 2000)
e("Rubies", "2000")
e("Emeralds", 2500)
e("Emeralds", "2500")
e("Sapphires", 1800)
e("Sapphires", "1800")
e("Diamonds", 2200)
e("Diamonds", "2200")
e("Gears", 2700)
e("Gears", "2700")
e("Trophies", 3200)
e("Trophies", "3200")
e("Capsules", 3500)
e("Capsules", "3500")
e("Roll", 3500)
e("Roll", "3500")
e("Rolls", 3500)
e("Rolls", "3500")
e("Elixirs", 2900)
e("Elixirs", "2900")
e("Runes", 4000)
e("Runes", "4000")
e("Shards", 4200)
e("Shards", "4200")
e("Fossils", 4500)
e("Fossils", "4500")
e("Relics", 4800)
e("Relics", "4800")
e(12345)
e(67890)
e({speed = 100, jump = 50})
e({stamina = 200, agility = 150})
e({strength = 500, defense = 300})
e({coins = 9999, gems = 5000})
e({health = 1000, mana = 500})
e({bullets = 300, grenades = 50})
e({wood = 100, stone = 50})
e({gold = 200, silver = 100})
e({apples = 10, oranges = 20})
e({potions = 5, elixirs = 10})
e({tickets = 3, tokens = 5})
e({materials = {wood = 100, stone = 50}})
e({resources = {gold = 200, silver = 100}})
e({items = {apples = 10, oranges = 20}})
e({inventory = {potions = 5, elixirs = 10}})
e({loot = {tickets = 3, tokens = 5}})
e({supplies = {bullets = 300, grenades = 50}})
e({assets = {health = 1000, mana = 500}})
e({attributes = {strength = 500, defense = 300}})
e("Egg", 90000000)
e("Egg", "300000000")
e("Blocks", 900)
e("Blocks", "900")
e("Streak", 900)
e("Streak", "900")
e("AutoFight", true)
e("AutoFight", false)
e("Trails", "Rainbow")
e("Trails", "Fire")
e("Gifts", {small = 10, large = 5})
e("Gifts", {common = 20, rare = 10})
e("Pets", {dog = 1, cat = 2})
e("Pets", {dragon = 1, phoenix = 1})
e("Season Pass", true)
e("Season Pass", false)
e("DailyReward", "Claimed")
e("DailyReward", "Unclaimed")
e("Spin", 500)
e("Spin", "500")
e("Boosts", {speed = 2, strength = 3})
e("Boosts", {health = 4, mana = 5})
e("Codes", {redeem = "XYZ123"})
e("Codes", {redeem = "ABC456"})
e("StarterPack", "Purchased")
e("StarterPack", "Not Purchased")
e(Vector3.new(100, 200, 300))
e(Vector3.new(400, 500, 600))
e(Vector2.new(50, 100))
e(Vector2.new(150, 200))
e(Vector3.new(700, 800, 900))
e(Vector2.new(250, 300))
e(Vector3.new(350, 450, 550))
e(Vector2.new(350, 400))
e(Vector3.new(150, 250, 350))
e(Vector2.new(450, 500))
e(Vector3.new(900, 800, 700))
e(Vector2.new(600, 550))
e(Vector3.new(650, 750, 850))
e(Vector2.new(500, 600))
e(Vector3.new(200, 300, 400))
e(Vector2.new(100, 200))
e(Vector3.new(800, 700, 600))
e(Vector2.new(350, 450))
e(Vector3.new(300, 400, 500))
e(Vector2.new(450, 550))
e(math.huge)
e(math.huge, "Cash")
e(9e9, "BestWin")
e("Balls", "9e9")
e("Balls", 9e9)
e("JumpPower", 300)
e("Prestige", 1000)  
e("JumpPower", "10000")    
e("WalkSpeed", 500)  
e("Gravity", 0)  
e("FlightMode", true)  
e("HealthRegen", 9e9)  
e("Shield", 9e9)  
e("Mana", 9e9)  
e("EnergyRegen", 9e9)  
e("DoubleCoins", true)  
e("TripleXP", true)  
e("PetLevel", 100)  
e("UnlockSkins", true)  
e("UnlockEmotes", true)  
e("AutoPickup", true)  
e("AutoSellTrash", true)  
e("Teleport", "SpawnPoint")  
e("UnlockZone", "FinalBoss")  
e("SetClan", "GodModeWarriors")  
e("UpgradeArmor", "Legendary")  
e("AddSkill", "Fireball", 9e9)  
e("CompleteEvent", "HalloweenEvent")  
e("DailyReward", true)  
e("EnableGodMode", true)  
e("UnlockBlueprint", "MegaSword")  
e("SetRank", "Grandmaster")  
e("UnlockVehicle", "RocketBike")  
e("CollectResource", "Wood", 9e9)  
e("ClaimAchievement", "Unstoppable")  
e("UnlockChapter", "Chapter5")  
e("SetDifficulty", "Easy")  
e("RedeemCode", "SUPERPOWER2025")  
e("EquipOutfit", "StealthSuit")  
e("AddPerk", "DamageBoost")  
e("SetEnvironment", "NightMode")  
e("SpawnVehicle", "Jet")  
e("AddTitle", "Champion")  
e("BoostEvent", "DoubleLoot")  
e("CompleteStage", "BossBattle")  
e("ActivateEvent", "MeteorShower")  
e("UnlockMode", "Endless")  
e("IncreaseLuck", 500)  
e("MaxAmmo", 9e9)  
e("InfiniteFuel", true)  
e("ClaimVoucher", "FreeCrystals")  
e("MaxAllStats", true)  
e("ResetCooldowns", true)  
e("EnableXray", true)  
e("AutoCraft", "MythicWeapon")  
e("InstantWin", true)  
e("UnlockTrophies", true)  
e("SpawnNPC", "Trader", {inventory = "RareItems"})  
e("CompleteLevel", "Level10")  
e("StartRaid", "DragonCave")  
e("AddBuff", "SpeedBoost", 300)  
e("RemoveDebuff", "Poison")  
e("ChangeWeather", "Snow")  
e("AddCompanion", "DragonPet")  
e("RevealMap", true)  
e("SetPrestige", 10)  
e("UnlockMount", "Phoenix")  
e("EquipItem", "GoldenBow")  
e("UnlockQuest", "HeroSaga")  
e("UnlockDungeon", "AncientRuins")  
e("ToggleGodRay", true)  
e("AddResource", "Diamond", 100000)  
e("EnableRadar", true)  
e("ActivateSuperMode", true)  
e("ResetProgress", false)  
e("InfiniteLives", true)  
e("MaxLevel", 999)  
e("UnlockAllWeapons", true)  
e("MaxSpeed", 1000)  
e("InstantReload", true)  
e("NoClip", true)  
e("AutoAim", true)  
e("UnlockAchievements", true)  
e("StealthMode", true)  
e("UnlockPets", true)  
e("UnlockAbilities", true)  
e("Invincible", true)  
e("SpawnItem", "MegaPotion")  
e("SetCurrency", "Gold", 9e9)  
e("UnlockAreas", true)  
e("AddXP", 9e9)  
e("MaxStamina", true)  
e("AutoRespawn", true)  
e("EquipSkin", "DiamondArmor")  
e("UnlockBadges", true)  
e("IncreaseRange", 500)  
e("DisableCooldowns", true)  
e("SuperJump", true)  
e("UnlimitedKeys", true)  
e("ActivatePowerUp", "TimeStop")  
e("UnlockAllLevels", true)  
e("SetRespawnPoint", "BossLair")  
e("UnlockAnimations", true)  
e("UnlockInventory", true)  
e("UnlockMap", "SecretIsland")  
e("SetVisibility", "Invisible")  
e("InfiniteDurability", true)  
e("UnlockBlueprints", true)  
e("AddFriendBonus", true)  
e("EnableEvent", "TreasureHunt")  
e("BoostXP", 10)  
e("UnlimitedProjectiles", true)  
e("UnlockEndgame", true)  
e("SpawnBoss", "Titan")  
e("UnlockTitles", true)  
e("UnlockVehicles", true)  
e("BoostDropRate", true)  
e("AddReputation", "Guild", 1000)  
e("SetEventProgress", "Complete")  
e("UnlockCrafting", true)  
e("UnlimitedEnergy", true)  
e("EnableFreeTrade", true)  
e("ActivateCheats", true)  
e("UnlockUpgrade", "HyperDrive")  
e("AddFuel", 99999)  
e("UnlockChallenges", true)  
e("SetArmor", "Ultimate")  
e("UnlockEmojis", true)  
e("SetAlliance", "Rebels")  
e("UnlockClass", "Assassin")  
e("SetMultiplier", "XP", 10)  
e("CompleteMission", "FinalBattle")  
e("UnlockMysteryBox", true)  
e("UnlockSideQuests", true)  
e("UnlockFastTravel", true)  
e("UnlockSecretMode", true)  
e("AddSkillPoints", 999)  
e("EnableAutoBattle", true)  
e("UnlockEliteMode", true)  
e("ActivatePerk", "CriticalHit")  
e("RemoveCooldown", "SpecialSkill")  
e("CompleteCollection", "Artifacts")  
e("UnlockPowers", true)  
e("UnlockGuild", true)  
e("AddFame", 10000)  
e("ActivateChallenge", "BossRush")  
e("SetWeapon", "InfinityBlade")  
e("UnlockRanks", true)  
e("AddQuestReward", "LegendaryLoot")  
e("EnableQuickRespawn", true)  
e("UnlockLegendaryGear", true)  
e("EnableFastLevelUp", true)  
e("RevealSecrets", true)  
e("UnlockEliteEnemies", true)  
e("SpawnTreasure", "GoldenChest")  
e("UnlockEpicMount", true)  
e("AutoFarm", true)  
e("AutoRebirth", true)  
e("AutoCollect", true)  
e("InstantSell", true)  
e("UnlimitedBackpack", true)  
e("IncreaseSpeed", 500)  
e("AutoHatch", true)  
e("TripleHatch", true)  
e("UnlockPets", true)  
e("PetMultiplier", 10)  
e("AddCoins", 9e9)  
e("AddGems", 9e9)  
e("UnlockAreas", true)  
e("AutoUpgrade", true)  
e("UnlockBoosts", true)  
e("PetXPBoost", true)  
e("IncreaseLuck", true)  
e("UnlockEggs", true)  
e("AddTokens", 99999)  
e("UnlimitedPowerUps", true)  
e("NoCooldown", true)  
e("EnableSuperClick", true)  
e("AutoClick", true)  
e("InstantUpgrade", true)  
e("UnlockGamepasses", true)  
e("UnlockMachines", true)  
e("AutoMerge", true)  
e("MaxStats", true)  
e("AutoPrestige", true)  
e("UnlockSkins", true)  
e("SetMultiplier", "Coins", 10)  
e("SetMultiplier", "Gems", 10)  
e("UnlockSecrets", true)  
e("MaxPetInventory", true)  
e("SetDamage", 99999)  
e("UnlockVehicles", true)  
e("UnlockTitles", true)  
e("UnlockEventRewards", true)  
e("MaxEnergy", true)  
e("AddBoost", "SpeedBoost")  
e("SetEventProgress", "Complete")  
e("EnablePetEquip", true)  
e("UnlockAchievements", true)  
e("UnlockTrading", true)  
e("UnlockRebirthShop", true)  
e("AddRebirthTokens", 9999)  
e("UnlockPortals", true)  
e("MaxRebirths", true)  
e("EnableFastActions", true)  
e("UnlockExclusivePets", true)  
e("AddEventCurrency", 999999)  
e("UnlockCrates", true)  
e("MaxTools", true)  
e("AutoQuest", true)  
e("UnlockVIPZone", true)  
e("SetEnergy", 99999)  
e("UnlockDecorations", true)  
e("ActivateMegaBoost", true)  
e("UnlockCraftingRecipes", true)  
e("UnlimitedStorage", true)  
e("EnableInfiniteRange", true)  
e("EnableInstantPickup", true)  
e("UnlockChallenges", true)  
e("SetHarvestSpeed", "Instant")  
e("UnlockGameModes", true)  
e("SpawnRareItem", "GoldenArtifact")  
e("UnlockLevelRewards", true)  
e("SetPetRarity", "Legendary")  
e("EnableInstantGrowth", true)  
e("UnlockMiningZones", true)  
e("UnlockFishingAreas", true)  
e("MaxFarmCapacity", true)  
e("UnlockCollectibles", true)  
e("AddPrestigePoints", 9999)  
e("MaxPetSlots", true)  
e("UnlockFusions", true)  
e("EnableAutoOpen", true)  
e("UnlockEventItems", true)  
e("UnlockQuestRewards", true)  
e("UnlockSeasonPass", true)  
e("UnlockSpeedBoost", true)  
e("UnlockInstantBuild", true)  
e("UnlockDailyRewards", true)  
e("UnlockSeasonalZones", true)  
e("UnlockElitePets", true)  
e("UnlockTradingCenter", true)  
e("Enable2xCoins", true)  
e("Enable2xGems", true)  
e("EnableAutoCollectEnergy", true)  
e("UnlockMegaPet", true)  
e("UnlockPetSkins", true)  
e("AddEventTickets", 999999)  
e("UnlockGoldenEggs", true)  
e("MaxUpgradeLevel", true)  
e("EnableSuperRebirth", true)  
e("UnlockAllIslands", true)  
e("AddSkillPoints", 1000)  
e("UnlockMegaTools", true)  
e("InstantHarvest", true)  
e("EnableFastRespawn", true)  
e("AddPrestigeLevel", 50)  
e("UnlockUltraBoost", true)  
e("UnlockTimeBoost", true)  
e("EnableInfiniteUpgrades", true)  
e("EnableInstantWin", true)  
e("UnlockUltraPets", true)  
e("EnableAutoSellMode", true)  
e("UnlockSuperSkills", true)  
e("UnlockPetEvolution", true)  
e("SetRebirthMultiplier", 100)  
e("UnlockPremiumZones", true)  
e("EnableSpeedRunMode", true)  
e("UnlockCosmeticItems", true)  
e("UnlockLegendaryCrafting", true)  
e("EnableXPBoost", true)  
e("UnlockTreasureMaps", true)  
e("UnlockHiddenQuests", true)  
e("UnlockResourceBoost", true)  
e("EnableGlobalEvents", true)  
e("UnlockBonusChests", true)  
e("AddSeasonPoints", 10000)  
e("EnableBossKillerMode", true)  
e("UnlockMegaBackpack", true)  
e("SetGameSpeed", 2)  
e("UnlockWorldExpansions", true)  
e("EnableInstantTeleport", true)  
e("UnlockSuperHatch", true)  
e("EnableAutoPrestigeRewards", true)  
e("UnlockTimeTravelZones", true)  
e("AddArtifactPower", 999999)  
e("UnlockEliteTitles", true)  
e("UnlockInfiniteTrading", true)  
e("SetCollectionRate", "Max")  
e("UnlockPetMastery", true)  
e("UnlockSecretAchievements", true)  
e("AddSuperCoins", 1000000)  
e("EnableHyperSpeed", true)  
e("UnlockAdvancedUpgrades", true)  
e("EnableDailyEventMode", true)  
e("UnlockSpecialAbilities", true)  
e("AddMysticShards", 99999)  
e("UnlockInstantEggHatch", true)  
e("EnableBonusStages", true)  
e("UnlockDualPetEquips", true)  
e("UnlockSuperPrestige", true)  
e("EnableTurboMode", true)  
e("UnlockPetCustomization", true)  
e("AddGoldenTokens", 9999)  
e("UnlockRareCraftingMaterials", true)  
e("EnableCustomStats", true)  
e("UnlockAllGamePassFeatures", true)  
e("EnableUnlimitedQuests", true)  
e("UnlockLegendaryRewards", true)  
e("EnableDoubleXP", true)  
e("UnlockEndgameItems", true)  
e("UnlockExclusiveZones", true)  
e("EnableAutoPetLeveling", true)  
e("UnlockSeasonExclusivePets", true)  
e("EnableInstantRewardClaim", true)  
e("UnlockSecretLocations", true)  
e("EnableRarePetDrops", true)  
e("UnlockSuperSkillsTree", true)  
e("EnableResourceDuplication", true)  
e("UnlockInfiniteLives", true)  
e("EnablePerfectCatch", true)  
e("UnlockHiddenNPCs", true)  
e("EnablePetTrainingBoost", true)  
e("UnlockCustomChallenges", true)  
e("EnableUltraEnergyMode", true)  
e("UnlockAllBadges", true)  
e("EnableGodMode", true)  
e("AddGameCurrency", 99999999)  
e("SetMaxLevel", true)  
e("UnlockExclusiveItems", true)  
e("EnableSpeedBoost", true)  
e("UnlockAllAbilities", true)  
e("EnableAutoWin", true)  
e("UnlockHiddenLevels", true)  
e("EnableNoCooldown", true)  
e("UnlockInfiniteAmmo", true)  
e("AddPremiumCurrency", 100000)  
e("UnlockAdminFeatures", true)  
e("EnableFastReload", true)  
e("SetGameDifficulty", "Easy")  
e("UnlockAllAchievements", true)  
e("EnableInfiniteResources", true)  
e("UnlockSpecialZones", true)  
e("EnableTeleportAnywhere", true)  
e("UnlockVIPAccess", true)  
e("AddEventPoints", 50000)  
e("EnableDamageMultiplier", 10)  
e("UnlockLimitedEditionItems", true)  
e("EnableRapidFire", true)  
e("SetGameTime", "Day")  
e("UnlockAllGameModes", true)  
e("EnableStealthMode", true)  
e("UnlockInstantRespawn", true)  
e("AddBattlePassXP", 1000000)  
e("EnableUnlimitedEnergy", true)  
e("UnlockSeasonalRewards", true)  
e("EnableOneHitKill", true)  
e("AddClanPoints", 10000)  
e("UnlockAdvancedWeapons", true)  
e("EnableCriticalHitChance", true)  
e("UnlockCustomizationOptions", true)  
e("EnableInstantCrafting", true)  
e("UnlockStoryMode", true)  
e("AddSocialPoints", 5000)  
e("UnlockEventExclusiveFeatures", true)  
e("EnableInvisibility", true)  
e("UnlockFastTravel", true)  
e("EnableHighJump", true)  
e("UnlockRareDrops", true)  
e("AddGuildXP", 100000)  
e("UnlockSuperSkillsTree", true)  
e("EnableMaxHP", true)  
e("UnlockHiddenTrophies", true)  
e("EnablePerfectAccuracy", true)  
e("AddGuildCoins", 99999)  
e("UnlockEliteRewards", true)  
e("EnableDynamicWeather", true)  
e("SetXPMultiplier", 5)  
e("UnlockExclusivePets", true)  
e("EnableAntiKnockback", true)  
e("AddGamePassItems", true)  
e("UnlockAllCustomizationSkins", true)  
e("EnableUltraSpeedMode", true)  
e("UnlockInfiniteFuel", true)  
e("SetDropRateMultiplier", 10)  
e("UnlockSecretEnding", true)  
e("EnableMultiHit", true)  
e("UnlockHiddenChallenges", true)  
e("EnableXPBoost", true)  
e("UnlockMaxRank", true)  
e("EnableInstantKillMode", true)  
e("UnlockSeasonLeaderboards", true)  
e("EnableUltimateAbilities", true)  
e("UnlockClanPerks", true)  
e("AddGuildPerks", 50)  
e("UnlockGlobalLeaderboardRank", true)  
e("EnableSuperJump", true)  
e("UnlockAllVehicles", true)  
e("EnableFlightMode", true)  
e("AddSecretTokens", 99999)  
e("UnlockSpecialAnimations", true)  
e("EnableEndlessMode", true)  
e("UnlockTimeLimitedFeatures", true)  
e("EnableAllWeaponAttachments", true)  
e("UnlockCustomHUD", true)  
e("EnablePetTrading", true)  
e("UnlockEventCrafting", true)  
e("EnableDoubleRewards", true)  
e("UnlockUltraAchievements", true)  
e("EnableMaxSpeed", true)  
e("UnlockHiddenEasterEggs", true)  
e("EnableGlobalBoosts", true)  
e("UnlockMegaTools", true)  
e("EnableFullMapAccess", true)  
e("SetInfiniteDurability", true)  
e("UnlockAllBlueprints", true)  
e("EnableBossLocator", true)  
e("UnlockUnlimitedDailyRewards", true)  
e("EnableInstantChallengeCompletion", true)  
e("UnlockTopTierItems", true)  
e("EnableUnlimitedSkillPoints", true)  
e("UnlockSpecialGameEvents", true)  
e("EnableAutoBattle", true)  
e("UnlockMythicalWeapons", true)  
e("EnableExtraInventorySpace", true)  
e("UnlockAdvancedSkillUpgrades", true)  
e("EnableCustomCharacterCreations", true)  
e("AddMoney", 99999999)  
e("SetMoneyMultiplier", 10)  
e("EnableAutoMoneyCollect", true)  
e("UnlockUnlimitedMoney", true)  
e("AddDailyMoneyBonus", 1000000)  
e("EnableMoneyRain", true)  
e("SetBankBalance", 999999999)  
e("AddPassiveIncome", 50000)  
e("EnableInstantMoneyPickup", true)  
e("AddEventMoneyReward", 1000000)  
e("UnlockVIPMoneyBoost", true)  
e("SetMoneyCap", 0)  
e("EnableDoubleMoney", true)  
e("AddTransactionBonus", 5000)  
e("UnlockExclusiveMoneyFeatures", true)  
e("EnableMoneyMultiplierBoost", 5)  
e("AddOfflineEarnings", 250000)  
e("SetInstantRichMode", true)  
e("EnableGlobalMoneyBoost", true)  
e("AddGroupMoneyBonus", 10000)  
e("UnlockSecretMoneyQuests", true)  
e("EnableInfiniteBankStorage", true)  
e("AddClanMoneyRewards", 500000)  
e("UnlockMoneyAchievements", true)  
e("EnablePrestigeMoneyBoost", true)  
e("SetAutoMoneyConversion", true)  
e("AddSeasonMoneyBonus", 100000)  
e("UnlockHiddenMoneySources", true)  
e("EnableMoneySharing", true)  
e("AddInvestmentProfit", 1000000)  
e("EnableMoneyRainEvent", true)  
e("SetHighestWealthRank", true)  
e("AddLimitedTimeMoney", 5000000)  
e("UnlockEventMoneyMultiplier", true)  
e("EnableMoneyAutoClaim", true)  
e("AddExclusiveMoneyPerks", true)  
e("SetMaxCashFlow", true)  
e("AddCashRewards", 750000)  
e("EnableInstantBanking", true)  
e("UnlockAllMoneyUpgrades", true)  
e("EnableCurrencyConverter", true)  
e("SetInfiniteWalletCapacity", true)  
e("AddMoneyFromMissions", 300000)  
e("EnableUltraMoneyBoost", true)  
e("AddMoneyDrops", true)  
e("UnlockGoldenCurrency", true)  
e("EnableDiamondMoneyBonus", true)  
e("SetVIPMoneyBenefits", true)  
e("AddHighRollerRewards", 10000000)  
e("EnableStackableMoneyBoosts", true)  
e("UnlockRareMoneyFinds", true)  
e("AddSuperWealthPoints", 99999)  
e("EnableCryptocurrencyEarnings", true)  
e("UnlockLuxuryMoneyOptions", true)  
e("SetAutoBankTransfer", true)  
e("AddDonationRewards", 5000)  
e("EnableCustomMoneyMultiplier", true)  
e("UnlockMultiCurrencyEarnings", true)  
e("AddUnlimitedBankBalance", true)  
e("EnableTeamMoneyBoost", true)  
e("AddPrestigeLevelMoney", 200000)  
e("UnlockGlobalMoneyEvents", true)  
e("EnableInfiniteCurrencyTrade", true)  
e("InfiniteHealth", true)  
e("InfiniteStamina", true)  
e("InfiniteMoney", true)  
e("MaxLevel", true)  
e("UnlockAllWeapons", true)  
e("UnlockAllItems", true)  
e("InfiniteAmmo", true)  
e("InfiniteResources", true)  
e("UnlockAllAbilities", true)  
e("InfiniteXP", true)  
e("NoCooldown", true)  
e("UnlockAllSkills", true)  
e("UnlockAllAchievements", true)  
e("MaxStats", true)  
e("GodMode", true)  
e("SpeedHack", true)  
e("Teleport", true)  
e("FlyMode", true)  
e("Invisible", true)  
e("UnlockAllCars", true)  
e("UnlockAllHouses", true)  
e("InfiniteTime", true)  
e("MaxMoney", true)  
e("DisableFallDamage", true)  
e("MaxInventory", true)  
e("UnlockAllAreas", true)  
e("InstantBuild", true)  
e("InstantCraft", true)  
e("NoHunger", true)  
e("NoThirst", true)  
e("InfiniteOxygen", true)  
e("UnlockAllVehicles", true)  
e("DisableGravity", true)  
e("IncreaseJumpHeight", true)  
e("NoClip", true)  
e("UnlockAllPets", true)  
e("UnlockAllOutfits", true)  
e("TeleportToPlayer", true)  
e("UnlockAllMounts", true)  
e("IncreaseSpeed", true)  
e("NoDamage", true)  
e("UnlockAllEmotes", true)  
e("UnlockAllBuildings", true)  
e("MaxStatsForAllPlayers", true)  
e("RemoveFogOfWar", true)  
e("NoWeaponCooldown", true)  
e("UnlockAllLevels", true)  
e("SetInfiniteResources", true)  
e("NoSkillCooldown", true)  
e("UnlockAllTrophies", true)  
e("UnlockAllRaces", true)  
e("UnlockAllClasses", true)  
e("TeleportToBase", true)  
e("UnlockAllTools", true)  
e("UnlockAllMounts", true)  
e("UnlockAllWeaponsAndItems", true)  
e("IncreaseDropRates", true)  
e("NoBuildLimit", true)  
e("SuperStrength", true)  
e("UnlockAllCurrencies", true)  
e("UnlockAllCraftingRecipes", true)  
e("InfiniteInventory", true)  
e("MaxBuildingCapacity", true)  
e("NoEnemies", true)  
e("DisableEnemySpawning", true)  
e("InfiniteHealthForTeammates", true)  
e("InstantKillEnemies", true)  
e("DisableWeaponDurability", true)  
e("UnlockAllResources", true)  
e("MaxPetLevel", true)  
e("UnlockAllQuests", true)  
e("UnlockAllWorlds", true)  
e("UnlimitedSkillPoints", true)  
e("UnlockAllUpgrades", true)  
e("DisableWeatherEffects", true)  
e("TeleportToShop", true)  
e("UnlockAllGameModes", true)  
e("UnlockAllChallenges", true)  
e("UnlimitedMoney", true)  
e("UnlockAllCraftingMaterials", true)  
e("InfiniteEnergy", true)  
e("UnlockAllChallengesAndRewards", true)  
e("UnlockAllStoryProgress", true)  
e("DisableCooldownsForItems", true)  
e("UnlockAllWeaponsAndSkills", true)  
e("UnlockAllSecretItems", true)  
e("InstantUpgrade", true)  
e("NoDamageForTeammates", true)  
e("UnlockSuperPowers", true)  
