--// Written by Norgumi
--// URF
--// Tested games ----->

-- https://www.roblox.com/games/13667319624/Knockout-Simulator [Infinite Strength / Wins]
-- https://www.roblox.com/games/15210092998/Ski-Race-Simulator [Infinite Strength / Wins]
-- https://www.roblox.com/games/14570378822/Bodybuilder-Simulator [Open Rare Eggs]
-- https://www.roblox.com/games/15338697306/Go-Kart-Race-Simulator [Infinite Wins]
-- https://www.roblox.com/games/15352354257/Ball-Eating-Simulator [Collect Badges / 3]
-- https://www.roblox.com/games/15154513235/Kamehameha-Simulator [Rejoin if kicked / Unlimited Spins/ Inf power / Inf Pets / Claim all daily rewards / Reclaim Gifts]
-- https://www.roblox.com/games/90042614856131/Fish-Evolution [Unlock all fishes, Rebirth Farming, XP Farming, Max Level]
-- https://www.roblox.com/games/91542981964579/I-WANNA-RUN-AWAY [Bigger Character (Only works with default avatar)]
-- https://www.roblox.com/games/138600641674950/AXOLOTL-Steal-Animals [Infinite Rebirths, Infinite Money, Gem Farming]
-- https://www.roblox.com/games/113909146512320/Steal-a-Meme [Infinite Money]
-- https://www.roblox.com/games/123741668193208/The-1-000-000-Jump-Rope [Spam kill everyone | WARNING : MONEY DECREASES]

local Remotes: {RemoteEvent | BindableEvent | RemoteFunction | BindableFunction} = {}
local CheckGame: boolean = false
local FireRemoteEvents: boolean = true
local FireBindableEvents: boolean = true
local FireRemoteFunctions: boolean = true
local FireBindableFunctions: boolean = true
local LogRemotes: boolean = true
local Blacklist: {string} = {"PlayEmote", "SendNotificationInfo", "VoiceChatTokenRequest", "IntegrityCheckProcessorKey2_LocalizationTableAnalyticsSender_LocalizationService", "IntegrityCheckProcessorKey2_DynamicTranslationSender_LocalizationService", "GetServerType", "CanChatWith", "SetPlayerBlockList", "UpdatePlayerBlockList", "NewPlayerGroupDetails", "NewPlayerCanManageDetails", "SendPlayerBlockList", "UpdateLocalPlayerBlockList", "SendPlayerProfileSettings", "SetDialogInUse", "GetServerVersion", "GetServerChannel", "WhisperChat", "ContactListInvokeIrisInvite", "ContactListIrisInviteTeleport", "UpdateCurrentCall", "RequestDeviceCameraOrientationCapability", "RequestDeviceCameraCFrame", "ReceiveLikelySpeakingUsers", "ReferredPlayerJoin", "OnNewMessage", "OnMessageDoneFiltering", "OnNewSystemMessage", "OnChannelJoined", "OnChannelLeft", "OnMuted", "OnUnmuted", "OnMainChannelSet", "ChannelNameColorUpdated", "SayMessageRequest", "SetBlockedUserIdsRequest", "GetInitDataRequest", "MutePlayerRequest", "UnMutePlayerRequest"}

local function GetRemotes(): ()
    local Success: boolean, Error: string = pcall(function()
        for _, Remote: Instance in pairs(getinstances()) do
            if Remote.Parent == game.ReplicatedStorage or Remote:IsDescendantOf(game.ReplicatedStorage) then
                if (Remote:IsA("RemoteEvent") and FireRemoteEvents) or (Remote:IsA("BindableEvent") and FireBindableEvents) or (Remote:IsA("RemoteFunction") and FireRemoteFunctions) or (Remote:IsA("BindableFunction") and FireBindableFunctions) then
                    if not table.find(Blacklist, Remote.Name) then
                        table.insert(Remotes, Remote)
                    end
                end
            end
        end
    end)
    if not Success then
        warn("Error getting remotes:", Error)
    end
end

local function Fire(...: any): ()
    local Args: {any} = {...}
    for _, Remote: RemoteEvent | BindableEvent | RemoteFunction | BindableFunction in pairs(Remotes) do
        spawn(function()
            pcall(function()
                if LogRemotes then
                    warn("Firing:", Remote.Name, "Type:", Remote.ClassName, "Args:", unpack(Args))
                end
                if Remote:IsA("RemoteEvent") then
                    Remote:FireServer(unpack(Args))
                elseif Remote:IsA("BindableEvent") then
                    Remote:Fire(unpack(Args))
                elseif Remote:IsA("RemoteFunction") then
                    Remote:InvokeServer(unpack(Args))
                elseif Remote:IsA("BindableFunction") then
                    Remote:Invoke(unpack(Args))
                end
            end)
        end)
    end
end

GetRemotes()

pcall(function()
    local HDAdmin: GuiObject = game:GetService("Players").LocalPlayer.PlayerGui:FindFirstChild("HDAdminInterface")
    if HDAdmin then
        warn("HD Admin detected - removing interface")
        HDAdmin:Destroy()
    end
end)

if CheckGame then
    local GameIds: {number} = {13667319624, 15210092998, 14570378822, 15338697306, 15352354257, 15154513235, 90042614856131, 91542981964579, 138600641674950}
    if not table.find(GameIds, game.PlaceId) then
        game.Players.LocalPlayer:Kick("Game not supported")
        return
    end
end

-- // Args \\

Fire("Power", 500)
Fire("Power", "500")
Fire("Eggs", 500)
Fire("Eggs", "500")
Fire("Certz", 500)
Fire("Best", 500)
Fire("Goals", 500)
Fire(900000000)
Fire("Kills", true)
Fire("Kills", 900000000000)
Fire("Kills", "900000000000")
Fire("Unlock All", true)
Fire("Unlock All", "true")
Fire("UnlockAll", true)
Fire("UnlockAll", "true")
Fire("9e9")
Fire("Record", "9943-0")
Fire("AddRecord", "9943-0")
Fire("GiveRecord", "9943-0")
Fire("SetRecord", "9943-0")
Fire("RecordReward", "9943-0")
Fire("RecordBonus", "9943-0")
Fire("RecordMultiplier", 10)
Fire("RecordBoost", 10)
Fire("CollectRecord", "9943-0")
Fire("ClaimRecord", "9943-0")
Fire("EarnRecord", "9943-0")
Fire("GetRecord", "9943-0")
Fire("RecordGain", "9943-0")
Fire("GainRecord", "9943-0")
Fire("MaxRecord", true)
Fire("RecordMax", true)
Fire("BestRecord", "9943-0")
Fire("TopRecord", "9943-0")
Fire("HighRecord", "9943-0")
Fire("NewRecord", "9943-0")
Fire("BreakRecord", "9943-0")
Fire("BeatRecord", "9943-0")
Fire("PersonalRecord", "9943-0")
Fire("WorldRecord", "9943-0")
Fire("GlobalRecord", "9943-0")
Fire("ServerRecord", "9943-0")
Fire("LeaderRecord", "9943-0")
Fire("ChampionRecord", "9943-0")
Fire("MasterRecord", "9943-0")
Fire("LegendRecord", "9943-0")
Fire("EpicRecord", "9943-0")
Fire("UltimateRecord", "9943-0")
Fire("SupremeRecord", "9943-0")
Fire("DivineRecord", "9943-0")
Fire("CosmicRecord", "9943-0")
Fire("InfiniteRecord", true)
Fire("UnlimitedRecord", true)
Fire("EndlessRecord", true)
Fire("EternalRecord", true)
Fire("ImmortalRecord", true)
Fire("GodRecord", true)
Fire("OVR", 99)
Fire("AddOVR", 99)
Fire("GiveOVR", 99)
Fire("SetOVR", 99)
Fire("OVRReward", 99)
Fire("OVRBonus", 99)
Fire("OVRMultiplier", 5)
Fire("OVRBoost", 5)
Fire("CollectOVR", 99)
Fire("ClaimOVR", 99)
Fire("EarnOVR", 99)
Fire("GetOVR", 99)
Fire("OVRGain", 99)
Fire("GainOVR", 99)
Fire("MaxOVR", true)
Fire("OVRMax", true)
Fire("BestOVR", 99)
Fire("TopOVR", 99)
Fire("HighOVR", 99)
Fire("NewOVR", 99)
Fire("BreakOVR", 99)
Fire("BeatOVR", 99)
Fire("PersonalOVR", 99)
Fire("WorldOVR", 99)
Fire("GlobalOVR", 99)
Fire("ServerOVR", 99)
Fire("LeaderOVR", 99)
Fire("ChampionOVR", 99)
Fire("MasterOVR", 99)
Fire("LegendOVR", 99)
Fire("EpicOVR", 99)
Fire("UltimateOVR", 99)
Fire("SupremeOVR", 99)
Fire("DivineOVR", 99)
Fire("CosmicOVR", 99)
Fire("InfiniteOVR", true)
Fire("UnlimitedOVR", true)
Fire("EndlessOVR", true)
Fire("EternalOVR", true)
Fire("ImmortalOVR", true)
Fire("GodOVR", true)
Fire("Money", 900000000000, true)
Fire("Strength", 900000000000)
Fire("Stamina", 900000000000)
Fire({health = 900000000000, armor = 900000000000})
Fire(true, false, true)
Fire("Ammo", {bullets = 9e9, rockets = 9e9})
Fire("PowerUp", "SpeedBoost", true)
Fire("MissionComplete", {time = "10:30", score = 9e9})
Fire("Upgrade", "Weapon", "Shotgun")
Fire("Toggle", "Lights", true)
Fire("PlaySound", "Explosion")
Fire("Spawn", "Enemy", {type = "boss", level = 9e9})
Fire("PurchaseItem", "Weapon", "AssaultRifle")
Fire("ActivateAbility", "Invisibility")
Fire("Unlock", "CharacterSkin", "Ninja")
Fire("ToggleUI", "Inventory", true)
Fire("RestartLevel")
Fire("SendChatMessage", "Hello, world!")
Fire("UpdateSettings", {musicVolume = 0.7, soundVolume = 0.5})
Fire("RespawnPlayer")
Fire("CompleteQuest", "MainQuest", true)
Fire("XP", 900000)
Fire("LevelUp", 9000)
Fire("SkillUnlock", "DoubleJump")
Fire("RankUp", "Elite")
Fire("ExperienceGain", 9e9)
Fire("SkillUpgrade", "Strength", 9e9)
Fire("AchievementUnlock", "FirstVictory")
Fire("Progress", "Quest", "Explore")
Fire("SkillPoint", "Allocate", "Strength", 9e9)
Fire("Equip", "Weapon", "Sword")
Fire("Unequip", "Weapon", "Shotgun")
Fire("Reload", "Weapon", "SniperRifle")
Fire("Modify", "Weapon", "Pistol", {damage = 9e9, accuracy = 0.9})
Fire("Swap", "Weapon", "SMG", "Shotgun")
Fire("AddAttachment", "Weapon", "AssaultRifle", "Scope")
Fire("RemoveAttachment", "Weapon", "SniperRifle", "Suppressor")
Fire("Craft", "Weapon", "RocketLauncher")
Fire("Drop", "Weapon", "GrenadeLauncher")
Fire("KickPlayer", "Player123")
Fire("BanPlayer", "Player456")
Fire("ModifyStat", "Health", 999999)
Fire("GiveItem", "DiamondSword")
Fire("AddCurrency", "Gold", 100000)
Fire("UnlockAll", "Characters")
Fire("AwardBadge", "EpicBadge123")
Fire("GrantPermission", "Admin")
Fire("DisableSecurity", true)
Fire("AddMoney", 9e9)
Fire("SetMoney", 9e9)
Fire("DoubleMoney")
Fire("StealMoney", true)
Fire("StealMoney", "true")
Fire("Daily", true)
Fire("DailyLogin", true)
Fire("DailyBonus", true)
Fire("DailyGift", true)
Fire("DailyPrize", true)
Fire("DailyChest", true)
Fire("DailyBox", true)
Fire("DailyClaim", true)
Fire("DailyCollect", true)
Fire("DailyGet", true)
Fire("DailyEarn", true)
Fire("DailyReceive", true)
Fire("DailyGrab", true)
Fire("DailyTake", true)
Fire("ClaimDaily", true)
Fire("CollectDaily", true)
Fire("GetDaily", true)
Fire("EarnDaily", true)
Fire("ReceiveDaily", true)
Fire("GrabDaily", true)
Fire("TakeDaily", true)
Fire("Streak", 100)
Fire("LoginStreak", 100)
Fire("DailyStreak", 100)
Fire("AddStreak", 100)
Fire("GiveStreak", 100)
Fire("SetStreak", 100)
Fire("StreakReward", 100)
Fire("StreakBonus", 100)
Fire("StreakMultiplier", 100)
Fire("StreakBoost", 100)
Fire("CollectStreak", 100)
Fire("ClaimStreak", 100)
Fire("EarnStreak", 100)
Fire("GetStreak", 100)
Fire("StreakGain", 100)
Fire("GainStreak", 100)
Fire("MaxStreak", true)
Fire("StreakMax", true)
Fire("InfiniteStreak", true)
Fire("UnlimitedStreak", true)
Fire("EndlessStreak", true)
Fire("Weekly", true)
Fire("WeeklyReward", true)
Fire("WeeklyBonus", true)
Fire("WeeklyGift", true)
Fire("WeeklyPrize", true)
Fire("WeeklyChest", true)
Fire("WeeklyBox", true)
Fire("WeeklyClaim", true)
Fire("WeeklyCollect", true)
Fire("ClaimWeekly", true)
Fire("CollectWeekly", true)
Fire("Monthly", true)
Fire("MonthlyReward", true)
Fire("MonthlyBonus", true)
Fire("MonthlyGift", true)
Fire("MonthlyPrize", true)
Fire("MonthlyChest", true)
Fire("MonthlyBox", true)
Fire("MonthlyClaim", true)
Fire("MonthlyCollect", true)
Fire("ClaimMonthly", true)
Fire("CollectMonthly", true)
Fire("Hourly", true)
Fire("HourlyReward", true)
Fire("HourlyBonus", true)
Fire("HourlyGift", true)
Fire("HourlyPrize", true)
Fire("HourlyChest", true)
Fire("HourlyBox", true)
Fire("HourlyClaim", true)
Fire("HourlyCollect", true)
Fire("ClaimHourly", true)
Fire("CollectHourly", true)
Fire("LoginReward", true)
Fire("LoginBonus", true)
Fire("LoginGift", true)
Fire("LoginPrize", true)
Fire("LoginChest", true)
Fire("LoginBox", true)
Fire("LoginClaim", true)
Fire("LoginCollect", true)
Fire("ClaimLogin", true)
Fire("CollectLogin", true)
Fire("Attendance", true)
Fire("AttendanceReward", true)
Fire("AttendanceBonus", true)
Fire("AttendanceGift", true)
Fire("AttendancePrize", true)
Fire("AttendanceChest", true)
Fire("AttendanceBox", true)
Fire("AttendanceClaim", true)
Fire("AttendanceCollect", true)
Fire("ClaimAttendance", true)
Fire("CollectAttendance", true)
Fire("ResetMoney", true)
Fire("ResetMoney", "true")
Fire("MultiplyMoney", 9e9)
Fire("HackMoney", 1000000)
Fire("AwardMoney", true)
Fire("AutoClick")
Fire("AutoCollect")
Fire("AutoSell")
Fire("InstantUpgrade")
Fire("SkipQuest")
Fire("AutoRebirth")
Fire("AutoUpgrade")
Fire("TeleportToZone", "HighLevelZone")
Fire("AutoFarm", "RareItem")
Fire("AutoPrestige")
Fire("AutoTrainSkill", "Strength")
Fire("AutoSpinWheel")
Fire("AutoOpenCrate", "LegendaryCrate")
Fire("AutoCompleteChallenge", "HardChallenge")
Fire("AutoLevelUp", "Character")
Fire("AutoClaimReward")
Fire("9e9")
Fire("True")
Fire("False")
Fire("9e9", true)
Fire(false)
Fire(true)
Fire("Points", 9e9)
Fire("Points", "90000000000")
Fire("Wins", 90000000)
Fire("Win", true)
Fire("Winner", true)
Fire("Balls", 9e9)
Fire("Owned", true)
Fire("Owned", 9e9)
Fire("Own", 9e9)
Fire("Own", true)
Fire("Value", 9e9)
Fire("Coin", 9e9)
Fire("Coins", 9e9)
Fire("AddCoins", 9e9)
Fire("GiveCoins", 9e9)
Fire("SetCoins", 9e9)
Fire("CoinReward", 9e9)
Fire("CoinBonus", 9e9)
Fire("CoinMultiplier", 9e9)
Fire("DoubleCoin", true)
Fire("TripleCoin", true)
Fire("CoinBoost", 9e9)
Fire("CollectCoin", 9e9)
Fire("ClaimCoin", 9e9)
Fire("EarnCoin", 9e9)
Fire("GetCoin", 9e9)
Fire("BuyCoin", 9e9)
Fire("SellCoin", 9e9)
Fire("SpendCoin", 9e9)
Fire("UseCoin", 9e9)
Fire("CoinPurchase", 9e9)
Fire("CoinExchange", 9e9)
Fire("CoinTrade", 9e9)
Fire("CoinBank", 9e9)
Fire("CoinWallet", 9e9)
Fire("CoinBalance", 9e9)
Fire("CoinAmount", 9e9)
Fire("CoinValue", 9e9)
Fire("CoinCount", 9e9)
Fire("CoinTotal", 9e9)
Fire("CoinGain", 9e9)
Fire("CoinIncome", 9e9)
Fire("CoinProfit", 9e9)
Fire("CoinEarnings", 9e9)
Fire("CoinRewards", 9e9)
Fire("CoinPrize", 9e9)
Fire("CoinJackpot", 9e9)
Fire("CoinLoot", 9e9)
Fire("CoinDrop", 9e9)
Fire("CoinFind", 9e9)
Fire("CoinMine", 9e9)
Fire("CoinFarm", 9e9)
Fire("CoinGrind", 9e9)
Fire("CoinHarvest", 9e9)
Fire("CoinGenerate", 9e9)
Fire("CoinCreate", 9e9)
Fire("CoinMake", 9e9)
Fire("CoinProduce", 9e9)
Fire("AutoCoin", true)
Fire("CoinAuto", true)
Fire("CoinClick", 9e9)
Fire("ClickCoin", 9e9)
Fire("TapCoin", 9e9)
Fire("CoinTap", 9e9)
Fire("CoinPress", 9e9)
Fire("PressCoin", 9e9)
Fire("EXP", 9e9)
Fire("Exp", 9e9)
Fire("Experience", 9e9)
Fire("AddEXP", 9e9)
Fire("GiveEXP", 9e9)
Fire("SetEXP", 9e9)
Fire("EXPReward", 9e9)
Fire("EXPBonus", 9e9)
Fire("EXPMultiplier", 9e9)
Fire("DoubleEXP", true)
Fire("TripleEXP", true)
Fire("EXPBoost", 9e9)
Fire("CollectEXP", 9e9)
Fire("ClaimEXP", 9e9)
Fire("EarnEXP", 9e9)
Fire("GetEXP", 9e9)
Fire("EXPGain", 9e9)
Fire("GainEXP", 9e9)
Fire("AddLevel", 100)
Fire("GiveLevel", 100)
Fire("SetLevel", 100)
Fire("LevelReward", 100)
Fire("LevelBonus", 100)
Fire("LevelMultiplier", 100)
Fire("LevelBoost", 100)
Fire("CollectLevel", 100)
Fire("ClaimLevel", 100)
Fire("EarnLevel", 100)
Fire("GetLevel", 100)
Fire("LevelGain", 100)
Fire("GainLevel", 100)
Fire("MaxLevel", true)
Fire("LevelMax", true)
Fire("InstantLevel", 100)
Fire("QuickLevel", 100)
Fire("FastLevel", 100)
Fire("AutoLevel", true)
Fire("LevelAuto", true)
Fire("SkipLevel", 100)
Fire("JumpLevel", 100)
Fire("ForceLevel", 100)
Fire("PushLevel", 100)
Fire("BoostLevel", 100)
Fire("PowerLevel", 100)
Fire("SuperLevel", 100)
Fire("MegaLevel", 100)
Fire("UltraLevel", 100)
Fire("HyperLevel", 100)
Fire("ExtremeLevel", 100)
Fire("InfiniteLevel", true)
Fire("UnlimitedLevel", true)
Fire("EndlessLevel", true)
Fire("EternalLevel", true)
Fire("ImmortalLevel", true)
Fire("GodLevel", true)
Fire("DivinLevel", true)
Fire("CelestialLevel", true)
Fire("CosmicLevel", true)
Fire("UniversalLevel", true)
Fire("AddCash", 9e9)
Fire("GiveCash", 9e9)
Fire("SetCash", 9e9)
Fire("CashReward", 9e9)
Fire("CashBonus", 9e9)
Fire("CashMultiplier", 9e9)
Fire("DoubleCash", true)
Fire("TripleCash", true)
Fire("CashBoost", 9e9)
Fire("CollectCash", 9e9)
Fire("ClaimCash", 9e9)
Fire("EarnCash", 9e9)
Fire("GetCash", 9e9)
Fire("CashGain", 9e9)
Fire("GainCash", 9e9)
Fire("CashDrop", 9e9)
Fire("CashLoot", 9e9)
Fire("CashPrize", 9e9)
Fire("CashJackpot", 9e9)
Fire("CashBank", 9e9)
Fire("CashWallet", 9e9)
Fire("CashBalance", 9e9)
Fire("CashAmount", 9e9)
Fire("CashValue", 9e9)
Fire("CashCount", 9e9)
Fire("CashTotal", 9e9)
Fire("AutoCash", true)
Fire("CashAuto", true)
Fire("CashClick", 9e9)
Fire("ClickCash", 9e9)
Fire("TapCash", 9e9)
Fire("CashTap", 9e9)
Fire("AddRebirth", 100)
Fire("GiveRebirth", 100)
Fire("SetRebirth", 100)
Fire("RebirthReward", 100)
Fire("RebirthBonus", 100)
Fire("RebirthMultiplier", 100)
Fire("RebirthBoost", 100)
Fire("CollectRebirth", 100)
Fire("ClaimRebirth", 100)
Fire("EarnRebirth", 100)
Fire("GetRebirth", 100)
Fire("RebirthGain", 100)
Fire("GainRebirth", 100)
Fire("MaxRebirth", true)
Fire("RebirthMax", true)
Fire("InstantRebirth", true)
Fire("QuickRebirth", true)
Fire("FastRebirth", true)
Fire("ForceRebirth", true)
Fire("PushRebirth", true)
Fire("TriggerRebirth", true)
Fire("ActivateRebirth", true)
Fire("DoRebirth", true)
Fire("MakeRebirth", true)
Fire("StartRebirth", true)
Fire("BeginRebirth", true)
Fire("InitRebirth", true)
Fire("ExecuteRebirth", true)
Fire("PerformRebirth", true)
Fire("Steal", 9e9)
Fire("StealCash", 9e9)
Fire("StealCoins", 9e9)
Fire("StealGold", 9e9)
Fire("StealGems", 9e9)
Fire("StealPoints", 9e9)
Fire("StealXP", 9e9)
Fire("StealLevel", 9e9)
Fire("StealPower", 9e9)
Fire("StealStrength", 9e9)
Fire("StealSpeed", 9e9)
Fire("StealAll", true)
Fire("StealEverything", true)
Fire("AutoSteal", true)
Fire("StealAuto", true)
Fire("Steals", 9e9)
Fire("AddSteals", 9e9)
Fire("GiveSteals", 9e9)
Fire("SetSteals", 9e9)
Fire("StealsReward", 9e9)
Fire("StealsBonus", 9e9)
Fire("StealsMultiplier", 9e9)
Fire("StealsBoost", 9e9)
Fire("CollectSteals", 9e9)
Fire("ClaimSteals", 9e9)
Fire("EarnSteals", 9e9)
Fire("GetSteals", 9e9)
Fire("StealsGain", 9e9)
Fire("GainSteals", 9e9)
Fire("MaxSteals", true)
Fire("StealsMax", true)
Fire("InfiniteSteals", true)
Fire("UnlimitedSteals", true)
Fire("EndlessSteals", true)
Fire("Value", true)
Fire("Stage", 100)
Fire("Trophy", math.huge)
Fire("Ammo", 9e9)
Fire(Vector3.new(300, 150, 600))
Fire("Time", 9e9)
Fire("Time", "9e9")
Fire("Chickens", 9e9)
Fire("Chickens", "9e9")
Fire("Lives", "9e9")
Fire("Lives", 9e9)
Fire("Life", "9e9")
Fire("Life", 9e9)
Fire("Crowns", 9e9)
Fire("Crowns", "9e9")
Fire("Level", 100)
Fire("Level", "100")
Fire("Rebirth", 100)
Fire("Rebirth", "100")
Fire("XP", 100)
Fire("XP", "100")
Fire("Spins", 100)
Fire("Spin", 100)
Fire("Speed", 900)
Fire("Redeem", "true")
Fire("Redeem", "900")
Fire("Redeem", 9000)
Fire("Redeemed", "true")
Fire("Redeemed", true)
Fire("Cash", 100)
Fire("Coins", 100)
Fire("Dinero", 100)
Fire("Rank", 100)
Fire("Goals", 100)
Fire("Damage", 9000000000000000000)
Fire("Win", 9000000000000000000)
Fire("Hunger", 90000000)
Fire("Body", 9000000000000)
Fire("KillStreak", 9000000000000)
Fire("Health", "900000000")
Fire("Health", 900000000)
Fire("Energy", "900000000")
Fire("Energy", 900000000)
Fire("Melee", "900000000")
Fire("Melee", 900000000)
Fire("Reputation", 9000000000000000000)
Fire("Distance", 9000000000000000000)
Fire("Nuke", "true")
Fire("Nuke", true)
Fire("Gems", 9000000000000000000)
Fire(90000000000)
Fire("90000000000")
Fire("Tokens", 5000)
Fire("Tokens", "5000")
Fire("Stars", 750)
Fire("Stars", "750")
Fire("Medals", 1200)
Fire("Medals", "1200")
Fire("Fragments", 300)
Fire("Fragments", "300")
Fire("Crystals", 10000)
Fire("Crystals", "10000")
Fire("Pearls", 1500)
Fire("Pearls", "1500")
Fire("Rubies", 2000)
Fire("Rubies", "2000")
Fire("Emeralds", 2500)
Fire("Emeralds", "2500")
Fire("Sapphires", 1800)
Fire("Sapphires", "1800")
Fire("Diamonds", 2200)
Fire("Diamonds", "2200")
Fire("Gears", 2700)
Fire("Gears", "2700")
Fire("Trophies", 3200)
Fire("Trophies", "3200")
Fire("Capsules", 3500)
Fire("Capsules", "3500")
Fire("Elixirs", 2900)
Fire("Elixirs", "2900")
Fire("Runes", 4000)
Fire("Runes", "4000")
Fire("Shards", 4200)
Fire("Shards", "4200")
Fire("Fossils", 4500)
Fire("Fossils", "4500")
Fire("Relics", 4800)
Fire("Relics", "4800")
Fire(12345)
Fire(67890)
Fire({speed = 100, jump = 50})
Fire({stamina = 200, agility = 150})
Fire({strength = 500, defense = 300})
Fire({coins = 9999, gems = 5000})
Fire({health = 1000, mana = 500})
Fire({bullets = 300, grenades = 50})
Fire({wood = 100, stone = 50})
Fire({gold = 200, silver = 100})
Fire({apples = 10, oranges = 20})
Fire({potions = 5, elixirs = 10})
Fire({tickets = 3, tokens = 5})
Fire({materials = {wood = 100, stone = 50}})
Fire({resources = {gold = 200, silver = 100}})
Fire({items = {apples = 10, oranges = 20}})
Fire({inventory = {potions = 5, elixirs = 10}})
Fire({loot = {tickets = 3, tokens = 5}})
Fire({supplies = {bullets = 300, grenades = 50}})
Fire({assets = {health = 1000, mana = 500}})
Fire({attributes = {strength = 500, defense = 300}})
Fire("Blocks", 900)
Fire("Blocks", "900")
Fire("AutoFight", true)
Fire("AutoFight", false)
Fire("Trails", "Rainbow")
Fire("Trails", "Fire")
Fire("Gifts", {small = 10, large = 5})
Fire("Gifts", {common = 20, rare = 10})
Fire("Pets", {dog = 1, cat = 2})
Fire("Pets", {dragon = 1, phoenix = 1})
Fire("Season Pass", true)
Fire("Season Pass", false)
Fire("DailyReward", "Claimed")
Fire("DailyReward", "Unclaimed")
Fire("Boosts", {speed = 2, strength = 3})
Fire("Boosts", {health = 4, mana = 5})
Fire("Codes", {redeem = "XYZ123"})
Fire("Codes", {redeem = "ABC456"})
Fire("StarterPack", "Purchased")
Fire("StarterPack", "Not Purchased")
Fire(Vector3.new(100, 200, 300))
Fire(Vector3.new(400, 500, 600))
Fire(Vector2.new(50, 100))
Fire(Vector2.new(150, 200))
Fire(Vector3.new(700, 800, 900))
Fire(Vector2.new(250, 300))
Fire(Vector3.new(350, 450, 550))
Fire(Vector2.new(350, 400))
Fire(Vector3.new(150, 250, 350))
Fire(Vector2.new(450, 500))
Fire(Vector3.new(900, 800, 700))
Fire(Vector2.new(600, 550))
Fire(Vector3.new(650, 750, 850))
Fire(Vector2.new(500, 600))
Fire(Vector3.new(200, 300, 400))
Fire(Vector2.new(100, 200))
Fire(Vector3.new(800, 700, 600))
Fire(Vector2.new(350, 450))
Fire(Vector3.new(300, 400, 500))
Fire(Vector2.new(450, 550))
Fire(math.huge)
Fire(math.huge, "Cash")
Fire(9e9, "BestWin")
Fire("Balls", "9e9")
Fire("Balls", 9e9)
Fire("TrainStrength",55000)
Fire("TrainSpeed",55000)
Fire("TrainStamina",55000)
Fire("TrainPower",55000)
Fire("DoPushup",true)
Fire("DoSitup",true)
Fire("Workout","FullBody",true)
Fire("Punch","Dummy",55000)
Fire("Lift","Weight",55000)
Fire("Boost","Strength",55000)
Fire("Farm","Wins",55000)
Fire("Grind","XP",55000)
Fire("BuyCoins",55000)
Fire("BuyGems",55000)
Fire("AddGold",55000)
Fire("GetCash",true)
Fire("CollectReward","Daily")
Fire("GiveMoney",55000)
Fire("CoinReward",55000)
Fire("AutoClaim","Login")
Fire("FreeCoins",true)
Fire("ClaimBonus","SpinReward")
Fire("AFKReward",55000)
Fire("AutoWin",true)
Fire("WinRace",true)
Fire("RebirthNow",true)
Fire("InstantRebirth",true)
Fire("ForceWin","Stage")
Fire("FinishLevel","Final")
Fire("PrestigeNow",true)
Fire("Ascend",true)
Fire("Promote","GodTier")
Fire("RankUpNow","Champion")
Fire("OpenEgg","Legendary")
Fire("Hatch","Epic")
Fire("AutoHatch",true)
Fire("OpenCrate","Rare")
Fire("BuyEgg","Galaxy")
Fire("GetPet","Dragon")
Fire("EquipPet","Phoenix")
Fire("MaxPets",true)
Fire("ClaimPet","Mystic")
Fire("FusePet","Pet1","Pet2")
Fire("ActivateBoost","Speed",true)
Fire("UseBoost","XP",true)
Fire("BoostStrength",55000)
Fire("DoubleXP",true)
Fire("DoubleCoins",true)
Fire("SpeedBoost","Max")
Fire("TriggerBoost","All",true)
Fire("HitEnemy","Boss",55000)
Fire("Kill","Mob",true)
Fire("Attack","Enemy",true)
Fire("Slash","Target",true)
Fire("FireGun","Shotgun",true)
Fire("Shoot","Rifle",55000)
Fire("Stab","NPC",true)
Fire("Damage","Target",55000)
Fire("KillMob","Zombie",true)
Fire("KillBoss","Dragon",true)
Fire("Explode","Area",true)
Fire("UseWeapon","Laser",true)
Fire("Throw","Bomb",true)
Fire("Fire","Weapon",true)
Fire("UpgradeNow",true)
Fire("UpgradeTool","Pickaxe",true)
Fire("UpgradeStrength",55000)
Fire("BuyUpgrade","Speed",true)
Fire("BuyTool","SuperPick",true)
Fire("BuyWeapon","Sniper",true)
Fire("ShopItem","Sword",true)
Fire("BuyItem","Jetpack",true)
Fire("Purchase","ItemPack",true)
Fire("LevelUpNow",true)
Fire("Mutate","Pet",true)
Fire("Evolve","Pet",true)
Fire("AscendNow",true)
Fire("CraftItem","MegaSword",true)
Fire("Forge","Armor",true)
Fire("AutoSell",true)
Fire("AutoGrind",true)
Fire("AutoFarm",true)
Fire("AutoClick",true)
Fire("AutoTap",true)
Fire("AutoTrain",true)
Fire("AutoRebirth",true)
Fire("AutoUpgrade",true)
Fire("AutoClaimReward",true)
Fire("AutoOpen",true)
Fire("AutoCollect",true)
Fire("AutoComplete",true)
Fire("AutoFinish",true)
Fire("GainStrength",55000)
Fire("AddSpeed",55000)
Fire("IncStamina",55000)
Fire("PowerUp",55000)
Fire("StartPushup",true)
Fire("DoSquat",true)
Fire("GrindPower","Energy",55000)
Fire("TrainStat","Agility",55000)
Fire("TapStrength",55000)
Fire("ClickTrain","Strength",55000)
Fire("LiftWeight","Heavy",55000)
Fire("BoostPower","Muscle",55000)
Fire("FarmCurrency","Wins",55000)
Fire("GrindXP","Main",55000)
Fire("CollectCash",true)
Fire("ClaimDaily",true)
Fire("GetReward","Online")
Fire("AddCoins",55000)
Fire("GrantGold",55000)
Fire("DepositGems",55000)
Fire("SpinReward","Big")
Fire("GiftClaim","Starter")
Fire("AFKCollect",true)
Fire("WinMatch",true)
Fire("CompleteStage","Final",true)
Fire("ClearZone","Boss",true)
Fire("ReachEnd",true)
Fire("InstantWin",true)
Fire("DoRebirth",true)
Fire("RebirthPlayer",true)
Fire("RebirthAction",true)
Fire("TriggerPrestige",true)
Fire("LevelUp","Main",55000)
Fire("RankUp","Maxed",true)
Fire("BoostRank",true)
Fire("OpenBox","Legendary")
Fire("OpenChest","Mythical")
Fire("HatchEgg","Void")
Fire("CrackCrate","Rare")
Fire("GetPetReward","Random")
Fire("EquipBestPet",true)
Fire("MergePet","Epic")
Fire("EvolvePet","Mythic")
Fire("MaxOutPet","Rare")
Fire("PetAction","Fuse",true)
Fire("UseSpeedBoost",true)
Fire("ActivateXPMultiplier",true)
Fire("ApplyBoost","Strength",55000)
Fire("StackBoosts",true)
Fire("BuyDoublePower",true)
Fire("TriggerPowerBoost","Full")
Fire("EnemyHit","Dummy",55000)
Fire("BossFight","Goblin",true)
Fire("ShootNPC","Shotgun")
Fire("UseSkill","Slash")
Fire("CastAttack","Fireball",true)
Fire("DealDamage","Mob",55000)
Fire("UseSword","Epic")
Fire("SwingTool","Axe",true)
Fire("Blast","Zone",true)
Fire("BuyItemPack","Legend")
Fire("UpgradeWeapon","Bow")
Fire("UpgradeGear","Boots")
Fire("UpgradeStat","Speed",55000)
Fire("BuyStatUpgrade","Stamina",true)
Fire("Enhance","Tool",true)
Fire("Smelt","Ore",true)
Fire("CraftWeapon","Laser")
Fire("ForgeArmor","Obsidian")
Fire("AutoBuy",true)
Fire("AutoTrainStat","Strength")
Fire("AutoBoost","XP")
Fire("AutoFight","Enemies")
Fire("AutoGrindLevel",true)
Fire("AutoGain","Power")
Fire("AutoFarmPet","Void")
Fire("AutoEquip","Best")
Fire("AutoMergePets",true)
Fire("AutoEnhance","Speed")
Fire("AutoAscend",true)
Fire("AutoPrestige",true)
Fire("AutoLevel",true)
Fire("AutoMax",true)
Fire("StartFarming","Power")
Fire("ActivateFarming","Gold")
Fire("InitPower",55000)
Fire("PushPower",55000)
Fire("SetStat","Energy",55000)
Fire("ApplyStat","Jump",55000)
Fire("ForceCollect",true)
Fire("PushValue","Power",55000)
Fire("TriggerValue","Speed",55000)
Fire("Click",55000)
Fire("AutoClick",true)
Fire("Tap",55000)
Fire("TapPower",55000)
Fire("TapStrength",55000)
Fire("AutoTap",true)
Fire("ClickStat","Power",55000)
Fire("SpamClick",true)
Fire("Clicker",true)
Fire("ClickLoop",true)
Fire("LoopTap",true)
Fire("ClickGain",55000)
Fire("ClickAction","Gain",55000)
Fire("AddClick",55000)
Fire("TapClick",55000)
Fire("PushClick","Energy",55000)
Fire("ClickBoost","Strength",55000)
Fire("ClickDamage",55000)
Fire("ClickCoins",55000)
Fire("TapCoins",55000)
Fire("GainClicks",55000)
Fire("ClickAmount",55000)
Fire("ManualClick",55000)
Fire("ClickPower",55000)
Fire("TapBoost",true)
Fire("MashClick",true)
Fire("FastClick",true)
Fire("HoldClick",true)
Fire("SwingClick",true)
Fire("ClickStatBoost",true)
Fire("TrainClick",55000)
Fire("ClickCollect","Points",55000)
Fire("FarmClicks",true)
Fire("ClickMultiplier",55000)
Fire("MultiplyClicks",true)
Fire("DoubleClick",true)
Fire("ClickEvent","Power",55000)
Fire("TriggerClick",true)
Fire("TapEvent","Energy",55000)
Fire("Press",55000)
Fire("PressClick",true)
Fire("PressBoost",true)
Fire("PowerClick",55000)
Fire("RapidClick",true)
Fire("ClickMeter","Max",true)
Fire("ClickZone","Main",true)
Fire("TapZone","Training",true)
Fire("LoopClick",true)
Fire("ClickPetBuff",true)
Fire("ClickSkill","FireClick",true)

warn("LOADED")
